ARG BASE_REGISTRY=registry1.dso.mil
ARG BASE_IMAGE=ironbank/opensource/palo-alto-networks/demisto/python3
ARG BASE_TAG=3.9.7.24076
FROM ${BASE_REGISTRY}/${BASE_IMAGE}:${BASE_TAG}

USER root

ENV DOCKER_IMAGE='demisto/iputils:1.0.0.24092'

ENV DOCKER_IMAGE_IRONBANK='opensource/palo-alto-networks/demisto/iputils:1.0.0.24092'

HEALTHCHECK NONE
