---
- name: Install Oh my zsh
  shell: curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh
  args:
    creates: ~/.oh-my-zsh

- name: Delete old ~/.zshrc
  file:
    path: ~/.zshrc
    state: absent

- name: Install auto suggestions and syntax high-lighting
  git:
    repo: "https://github.com/zsh-users/{{ item }}.git"
    dest: ~/.oh-my-zsh/custom/plugins/{{ item }}
  with_items:
    - zsh-autosuggestions
    - zsh-syntax-highlighting

- name: Init ~/.zshrc file
  copy:
    src: "{{ item }}"
    dest: "~/{{ item }}"
    force: yes
  with_items:
    - .zshrc
    - .bash_profile
    - .zprofile
    - .profile

- name: Set zsh as default shell
  become: yes
  command: "chsh -s /bin/zsh {{ ansible_env.USER }}"
