# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)
# 
# Set MYSQL_DATABASE, MYSQL_USER, and MYSQL_PASSWORD environment variables in
# .env file, place in the same directory where docker-compose.yml is located and
# run docker-compose up -d 
#
version: '3.7'

# Define services
services:
  # Quadra service
  quadra:
    # Configuration for building the docker image for quadra service
    build:
      context: quadra # Use an image built from the Dockerfile in the 'quadra' directory
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - db # this service depends on db. Start db first.
    environment: # Pass environment variables to the service
      SPRING_DATASOURCE_URL: "jdbc:mysql://db:3306/${MYSQL_DATABASE}"
      SPRING_DATASOURCE_USERNAME: "${MYSQL_USER}"
      SPRING_DATASOURCE_PASSWORD: "${MYSQL_PASSWORD}"    
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - quadra-db
       
  # Database service (MySQL)
  db:
    image: mysql:8.0.22
    ports:
      - "3306:3306"
    restart: always    
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - quadra-db
      
# Volumes
volumes:
  db-data:      
        
# Networks to be created to facilitate communication between containers        	
networks:
  quadra-db:
  