FROM demisto/ml:1.0.0.12177

RUN pip install --trusted-host github.com https://github.com/explosion/spacy-models/releases/download/fr_core_news_sm-2.1.0/fr_core_news_sm-2.1.0.tar.gz --default-timeout=100

RUN pip install --trusted-host github.com https://github.com/explosion/spacy-models/releases/download/de_core_news_sm-2.1.0/de_core_news_sm-2.1.0.tar.gz --default-timeout=100

RUN pip install --trusted-host github.com https://github.com/explosion/spacy-models/releases/download/es_core_news_sm-2.1.0/es_core_news_sm-2.1.0.tar.gz --default-timeout=100

RUN pip install --trusted-host github.com https://github.com/explosion/spacy-models/releases/download/pt_core_news_sm-2.1.0/pt_core_news_sm-2.1.0.tar.gz --default-timeout=100

RUN pip install --trusted-host github.com https://github.com/explosion/spacy-models/releases/download/it_core_news_sm-2.1.0/it_core_news_sm-2.1.0.tar.gz --default-timeout=100

RUN pip install --trusted-host github.com https://github.com/explosion/spacy-models/releases/download/nl_core_news_sm-2.1.0/nl_core_news_sm-2.1.0.tar.gz --default-timeout=100


