# Last modified: 2026-07-26T12:50:00.594456+00:00

FROM demisto/powershell-ubuntu:7.5.0.11326619

RUN pwsh -c "Install-Module MicrosoftTeams -Force"

# CIAC-17423 parallel-build POC: touch to include in parallel capacity test
