variables:
  CURRENT_BRANCH_NAME: "fix-cve-report-missing-attachments"

include:
  - file: "/.gitlab/ci/dockerfiles/.gitlab-ci.yml"
    ref: "fix-cve-report-missing-attachments"
    project: "${CI_PROJECT_NAMESPACE}/infra"
