variables:
  CURRENT_BRANCH_NAME: fix/build_docker_requirements_txt

include:
  - file: "/.gitlab/ci/dockerfiles/.gitlab-ci.yml"
    ref: fix/build_docker_requirements_txt
    project: "${CI_PROJECT_NAMESPACE}/infra"
