variables:
  CURRENT_BRANCH_NAME: docker-files-upload-no-terminal  # FIXME $INFRA_BRANCH

include:
  - file: "/.gitlab/ci/dockerfiles/.gitlab-ci.yml"
    ref: docker-files-upload-no-terminal # FIXME $INFRA_BRANCH
    project: "${CI_PROJECT_NAMESPACE}/infra"
