ARG BASE_REGISTRY=registry1.dso.mil
ARG BASE_IMAGE=ironbank/opensource/palo-alto-networks/demisto/python3
ARG BASE_TAG=3.9.7.24076
FROM ${BASE_REGISTRY}/${BASE_IMAGE}:${BASE_TAG}

USER root

RUN dnf install -y --nodocs poppler poppler-utils && \
        dnf clean all && \
        rm -rf /var/cache/dnf

ENV DOCKER_IMAGE='demisto/readpdf:1.0.0.24272'

ENV DOCKER_IMAGE_IRONBANK='opensource/palo-alto-networks/demisto/readpdf:1.0.0.24272'

HEALTHCHECK NONE
