JUSTIFICATIONS = {
      'GHSA-5xp3-jfq3-5q8x': 'The pip in the XSOAR docker images in the Ironbank environment is not allowed to communicate with any Git and the only use for pip is to installed packages that are downloaded in advance and pre approved by the Ironbank team.',
      'cbff271f45d32e78dcc1979dbca9c14d': 'The docker images we create are being used by our server: Cortex XSOAR. More info at: https://docs.paloaltonetworks.com/cortex/cortex-xsoar/6-2/cortex-xsoar-admin/docker/docker-images-in-demisto.html. Referring to the product design, the dockers are run by the Cortex XSOAR server and the server has some constraints on the expected format of the docker images. The server assumes that the default user of an image is "root". The product does have a configuration to run as non-root the docker images. See: https://docs.paloaltonetworks.com/cortex/cortex-xsoar/6-2/cortex-xsoar-admin/docker/docker-hardening-guide/run-docker-with-non-root-internal-users.html. But for the rare cases that an image needs to run with a "root" internal user, the product assumes the default configured user is "root" and will not pass this as a parameter to the "docker run" command. For this reason, we want to maintain this compatibility and set the default user to "root".',
      'CVE-2020-14422': 'PIP 9.0.3 is not in use, the PIP was upgraded manually to version 20.3.4.',
      'CVE-2021-43618': 'The XSOAR software does not use this module, this module was installed as dependency for systemd.',
      'CVE-2021-3733': 'The XOSAR software is using this module to communicate with internal 3rd party applications only that are running on the same network and it is not in use for communication with public services. We do not see any risk or potential attack from the services that XSOAR is communicating with.',
      'CVE-2021-3737': 'The XOSAR software is using this module to communicate with internal 3rd party applications only that are running on the same network and it is not in use for communication with public services. We do not see any risk or potential attack from the services that XSOAR is communicating with.',
      'CVE-2019-9674': 'The XSOAR software is not using python3-libs, the only use for python 3 is by yum/rpm. The XSOAR software is not using any of the above tools, the only use for them is at the Docker build stage.',
      'CVE-2020-27619': 'The XSOAR software is not using python3-libs, the only use for python 3 is by yum/rpm. The XSOAR software is not using any of the above tools, the only use for them is at the Docker build stage.',
      'CVE-2020-8492': 'The XOSAR software is using this module to communicate with internal 3rd party applications only that are running on the same network and it is not in use for communication with public services. We do not see any risk or potential attack from the services that XSOAR is communicating with.',
      'CVE-2021-42694': 'The XOSAR software basiclly using the docker image to runs python code, the output of the python script are manipulated and displayed on the client browser side.',
      'CVE-2020-17049': 'The XSOAR software does not use this module, this module was installed as dependency for systemd.',
      'CVE-2021-4019': 'The XSOAR software doesnt use the vim module in the runtime executions, the only use for vim is only for debugging purpose which done manually by our engeneers on the docker itself.',
      'CVE-2018-5360': 'The XSOAR software does not convert the PDF files to TIFF, The only use for the PDF reader is to extract information from PDF files.',
      'CVE-2018-19210': 'The XSOAR software does not convert the PDF files to TIFF, The only use for the PDF reader is to extract information from PDF files.',
      'CVE-2018-17101': 'The XSOAR software does not convert the PDF files to TIFF, The only use for the PDF reader is to extract information from PDF files.',
      'CVE-2018-16335': 'The XSOAR software does not convert the PDF files to TIFF, The only use for the PDF reader is to extract information from PDF files.',
      'CVE-2018-15209': 'The XSOAR software does not convert the PDF files to TIFF, The only use for the PDF reader is to extract information from PDF files.',
      'CVE-2019-6128': 'The XSOAR software does not convert the PDF files to TIFF, The only use for the PDF reader is to extract information from PDF files.',
      'CVE-2018-10801': 'The XSOAR software does not convert the PDF files to TIFF, The only use for the PDF reader is to extract information from PDF files.',
      'CVE-2018-10779': 'The XSOAR software does not convert the PDF files to TIFF, The only use for the PDF reader is to extract information from PDF files.',
      'CVE-2020-19131': 'The XSOAR software does not convert the PDF files to TIFF, The only use for the PDF reader is to extract information from PDF files.',
      'CVE-2017-17095': 'The XSOAR software does not convert the PDF files to TIFF, The only use for the PDF reader is to extract information from PDF files.',
      'CVE-2020-35521': 'The XSOAR software does not convert the PDF files to TIFF, The only use for the PDF reader is to extract information from PDF files.',
      'CVE-2020-35522': 'The XSOAR software does not convert the PDF files to TIFF, The only use for the PDF reader is to extract information from PDF files.',
      'CVE-2020-35523': 'The XSOAR software does not convert the PDF files to TIFF, The only use for the PDF reader is to extract information from PDF files.',
      'CVE-2020-35524': 'The XSOAR software does not convert the PDF files to TIFF, The only use for the PDF reader is to extract information from PDF files.',
      'CVE-2018-16435': 'The XSOAR software does not convert the PDF files to TIFF, The only use for the PDF reader is to extract information from PDF files.',
      'CVE-2018-19876': 'The XSOAR software does not shows or display the pdf on the screen, The only use for the PDF reader is to extract information from PDF files.',
      'CVE-2018-18064': 'The XSOAR software does not shows or display the pdf on the screen, The only use for the PDF reader is to extract information from PDF files.',
      'CVE-2019-6461': 'The XSOAR software does not shows or display the pdf on the screen, The only use for the PDF reader is to extract information from PDF files.',
      'CVE-2019-6462': 'The XSOAR software does not shows or display the pdf on the screen, The only use for the PDF reader is to extract information from PDF files.',
      'CVE-2019-2201': 'The XSOAR software is running on x86-64',
      'CVE-2020-13790': 'The XSOAR software does not shows or display the pdf on the screen, The only use for the PDF reader is to extract information from PDF files.',
      'CVE-2020-17541': 'The XSOAR software does not show or display any image on the screen from the pdf file, The only use for the PDF reader is to extract information from PDF files.',
      'CVE-2018-20846': 'The XSOAR software does not show or display any image on the screen from the pdf file, The only use for the PDF reader is to extract information from PDF files.',
      'CVE-2021-29338': 'The XSOAR software does not show or display any image on the screen from the pdf file, The only use for the PDF reader is to extract information from PDF files.',
      'CVE-2019-9543': 'The XSOAR software does not show or display any image on the screen from the pdf file, The only use for the PDF reader is to extract information from PDF files.',
      'CVE-2019-11026': 'The XSOAR software does not show or display the text as defined in the pdf file, The only use for the PDF reader is to extract information from PDF files.',
      'CVE-2020-35492': 'The XSOAR software does not shows or display the pdf on the screen, The only use for the PDF reader is to extract information from PDF files.',
      'CVE-2020-1712': 'The XSOAR software does not rely on systemd, the only use for systemd is for the operation system itself, the XSOAR software is not installing any packge in realtime that use systemd so there is no concern for this vulnerability.',
      'CVE-2019-20386': 'The XSOAR software does not rely on systemd, the only use for systemd is for the operation system itself, the XSOAR software is not installing any packge in realtime that use systemd so there is no concern for this vulnerability.',
      'CCE-86233-4': 'The XSOAR software does not manage or add any user to the docker except the demisto user which is used to manage the docker image also it does not has shell login capabilities. One more important thing the docker images are not persistent running so they get refreshed often so there is not no concern from save password.',
      'CVE-2020-27748': 'XSOAR Software does not rendering email or maintain email files or email messages using this commponent.',
      'CVE-2019-5068': 'XSOAR Software does not use this docker to browse or exploring web pages or ftp site the only use for this docker is to render html content.',
      'CCE-85987-6': 'The XSOAR software does not manage or add any user to the docker except the demisto user which is used to manage the docker image also it does not has shell login capabilities. One more important thing the docker images are not persistent running so they get refreshed often so there is not no concern from save password.',
      'CVE-2018-20839': 'The XSOAR software uses dockers with VT support disabled.',
      'CVE-2021-3997': 'The XSOAR software uses the image only once, which mean the XSOAR does not rebooting the system, also our images are based on UBI 8.5 which is more secured for this vulnerability.',
      'CVE-2021-3672': 'The way XSOAR software uses the c-ares is in direct, The XSOAR software uses this docker to parse pcap files, usually pcap files have the resolved ips stored in the traffic packets.',
      'CVE-2021-43818': 'The XSOAR software uses the lxml module only to parse xml content.',
      'GHSA-55x5-fj6c-h6m8': 'The XSOAR software uses the lxml module only to parse xml content.'
                }


SHEET_JUSTIFICATIONS_MAPPERS = {'Anchore Compliance Results': {'column_name': 'trigger_id'},
                                'Twistlock Vulnerability Results': {'column_name': 'id'},
                                'Anchore CVE Results': {'column_name': 'cve'},
                                'OpenSCAP - DISA Compliance': {'column_name': 'identifiers'}}
