FROM demisto/python3:3.10.11.59581

RUN mkdir /var/opt/etl

RUN wget -O /var/opt/etl/etl2pcap.py https://raw.githubusercontent.com/aaptel/etl2pcap/45c1a843078c757a0e5e49b30c89c77221ae9afc/etl2pcap.py
