on:
  push:
jobs:
  docker_build:
      env:
        BRANCH_NAME: ${{github.ref_name}}
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: Validate Approved Licenses File
          run:  python -m jsonschema -i docker/approved_licenses.json docker/approved_licenses.schema.json
        - name: Validate Dependabot Config
          run: ./docker/verify_dependabot.sh
        - name: Build Docker Images
          run: ./docker/build_docker.sh
        
        - name: Step 1 - Create a temporary artifact downloads folder
          run: mkdir downloads
          
        - name: step 2 - Add artifacts to publish to the temp folder
          run: |
            cd downloads
            echo 'alpha'    > alpha.html
            echo 'bravo'    > bravo.html
            echo 'charlie'  > charlie.html
            cd ..
      
        - name: Step 3 - Use the Upload Artifact GitHub Action
          uses: actions/upload-artifact@v2
          with: 
            name: assets-for-download

      #     no_output_timeout: 60m
      # - store_artifacts:
      #     path: artifacts
      #     destination: docker_images
  # workflows:
  # version: 2
  # full_build: