name: Handle New Contribution

on:
  pull_request_target:
    types: [opened, ready_for_review]

permissions:
  pull-requests: write
  contents: write

jobs:
  assign:
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.repo.fork == true
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Print Context
        run: |
          echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
      - name: Add an assignee and a Contribution label
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          PR_URL: ${{github.event.pull_request.html_url}}
        run: |
          echo "clone content in order to get the content_roles.json"
          git clone https://github.com/demisto/content.git
          content_roles=$( cat content/.github/content_roles.json )
          echo "$content_roles"
          
          echo "==== $(date): Starting pipenv setup... ===="
          python -m pip install --upgrade pip
          pip install pipenv
          pwd
          cd "$GITHUB_WORKSPACE/.github/workflows/handle_new_contribution"
          pipenv install
          
          echo "Getting the contribution TL"
          pipenv run python ./handle_new_contribution.py -c "$content_roles"
          contrib_tl=$( cat contrib_tl.txt )
          echo "$contrib_tl"
          find . -name "contrib_tl.txt" -type f -delete
          echo "Finished retrieving the contribution TL username"
          
          echo "Add an assignee and a Contribution label"
          gh pr edit --add-assignee "$contrib_tl" --add-label Contribution "$PR_URL"
