name: Handle New Contribution

on:
  pull_request_target:
    types: [opened, ready_for_review]

permissions:
  pull-requests: write
  contents: write

jobs:
  assign_and_label:
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.repo.fork == true
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Print Context
        run: |
          echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
      - name: Add an assignee and a Contribution label
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          PR_URL: ${{github.event.pull_request.html_url}}
        run: |
          echo "get content_roles.json using curl"
          contrib_tl=$( curl https://raw.githubusercontent.com/demisto/content/master/.github/content_roles.json | jq .CONTRIBUTION_TL -r )
          echo "$contrib_tl"
          echo "Finished retrieving the contribution TL username"
          
          if [ $contrib_tl ]; then
            echo "Add an assignee and a Contribution label"
            gh pr edit --add-assignee "$contrib_tl" --add-label Contribution "$PR_URL"
          else
            echo "There was a problem with retrieving the GitHub user name of the contribution TL."
          fi
