name: Native docker validator
on:
  pull_request:
    branches:
      - master
    types: [opened, reopened, synchronize, labeled, unlabeled]

jobs:
  native_docker_image_labeled:
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]' && contains(github.event.pull_request.title, 'autoupdate') == false && github.repository == 'demisto/dockerFiles'
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@2f7c5bfce28377bc069a65ba478de0a74aa0ca32 # v46.0.1
      - name: Set up Python 3.11
        uses: actions/setup-python@3542bca2639a428e1796aaa6a2ffef0c0f575566 # v3
        with:
          python-version: "3.11"
      - name: Run native_docker_labeled Script
        if: contains(github.event.pull_request.labels.*.name, 'native image approved') == false
        env:
          CHANGED_FILES: "${{ steps.changed-files.outputs.all_changed_files }}"
        run: |
          echo "==== $(date): Starting pipenv setup... ===="
          python -m pip install --upgrade pip
          pip install pipenv
          pwd
          cd "$GITHUB_WORKSPACE/.github/workflows/native-docker-labeled"
          pipenv install
          echo "==== $(date): Running validator... ===="
          pipenv run ./native_docker_labeled.py -c "$CHANGED_FILES"


