name: Compare Dependency Constraints
on:
  pull_request:
    branches:
      - master
jobs:
  compare_dependency_constraints_script:
    runs-on: ubuntu-latest
    if: github.repository == 'demisto/dockerFiles'
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.*"
      - name: Install dependencies with pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install
      - name: Compare dependency constraints
        run: pipenv run python utils/compare_dependency_constraints.py