name: Compare Dependency Constraints
on:
  pull_request:
    branches:
      - master
jobs:
  compare_dependency_constraints_script:
    runs-on: ubuntu-latest
    if: github.repository == 'demisto/dockerFiles'
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Install dependencies with pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install
      - name: Run compare_dependency_constraints Script.
        run: |
          echo "==== $(date): Starting environment setup... ===="
          cd "$GITHUB_WORKSPACE/utils/"
          echo "==== $(date): Running chceking Native dependency ===="
          pipenv run python compare_dependency_constraints.py